---
deployment:
  tasks:
    - export DEPLOYPATH=/home/xx17psecd7c6/public_html/sistemaescuna
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R dist/* $DEPLOYPATH/
    - /bin/cp dist/.htaccess $DEPLOYPATH/.htaccess
