---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html/sistemaescuna
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R dist/* $DEPLOYPATH/
    - /bin/cp dist/.htaccess $DEPLOYPATH/.htaccess
